; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-devkit-v1

<<<<<<< HEAD
[env:esp32-c3-devkitm-1]
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.3
	stblassitude/Adafruit SSD1306 Wemos Mini OLED@^1.1.2
	rfetick/MPU6050_light@^1.1.0
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	adafruit/Adafruit SSD1306@^2.5.15
	bblanchon/ArduinoJson@^7.4.2
	adafruit/Adafruit BusIO@^1.17.4

=======
>>>>>>> codex/send-test-code-for-esp32-modules-qnbph3
[env:esp32-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
<<<<<<< HEAD
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.3
	stblassitude/Adafruit SSD1306 Wemos Mini OLED@^1.1.2
	rfetick/MPU6050_light@^1.1.0
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	adafruit/Adafruit SSD1306@^2.5.15
	bblanchon/ArduinoJson@^7.4.2
	adafruit/Adafruit BusIO@^1.17.4
=======


; Declare libs aqui quando precisar
; lib_deps =
;   adafruit/Adafruit ADS1X15@^2.5.0
>>>>>>> codex/send-test-code-for-esp32-modules-qnbph3
